load("@org_tensorflow//tensorflow/core/platform:rules_cc.bzl", "cc_library")

package(default_visibility = ["//mononn_engine:__subpackages__"])

cc_library(
    name = "cnpy",
    srcs = ["cnpy.cc"],
    hdrs = ["cnpy.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//mononn_engine/helpers:macros",
    ],
)
